package com.newardassociates.demo;

import java.util.Random;
import java.util.logging.Logger;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private static Logger LOGGER = Logger.getLogger(App.class.getCanonicalName());

    public static void main(String[] args) {
        LOGGER.entering(App.class.getSimpleName(), "main", args);

        System.out.println("WARNING: Abandon hope, all ye who enter here....");
        String whichBug = "";
        if (args.length == 0) {
            LOGGER.info("No option specified; selecting at random");
            int which = new Random().nextInt(2);
            switch (which) {
                case 0:
                    RunawayAllocation.go(args);
                    break;
                case 1:
                    NullInvocation.go(args);
                    break;
                default:
                    System.out.println("How'd we do that?!?");
                    break;
            }
        } else {
            LOGGER.info("Looking to run option " + args[0]);
            switch (args[0]) {
                case "--runaway":
                    RunawayAllocation.go(args);
                    break;
                case "--null":
                    NullInvocation.go(args);
                    break;
                default:
                    System.out.println("Unrecongized option: " + args[0]);
            }
        }

        LOGGER.exiting("Main", "main");
    }
}
