package com.newardassociates.demo;

import java.util.Random;
import java.util.logging.Logger;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private static Logger LOGGER = Logger.getLogger(App.class.getCanonicalName());

    public static void main(String[] args) {
        LOGGER.entering(App.class.getSimpleName(), "main", args);

        System.out.println("**** BE WARNED: Abandon hope, all ye who enter here....");

        String whichBug = "";
        String[] options = {
                "--runaway", "--null", "--eatit", "--deadlock"
        };
        if (args.length == 0) {
            LOGGER.info("No option specified; selecting at random");
            whichBug = options[new Random().nextInt(options.length)];
        } else {
            whichBug = args[0];
        }

        LOGGER.info("Looking to run option " + whichBug);
        switch (whichBug) {
            case "--runaway":
                RunawayAllocation.go(args);
                break;
            case "--null":
                NullInvocation.go(args);
                break;
            case "--eatit":
                EatIt.go(args);
                break;
            case "--deadlock":
                Deadlock.go(args);
                break;
            default:
                System.out.println("Unrecongized option: " + args[0]);
        }

        LOGGER.exiting("Main", "main");
    }
}
